INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00132',	TRIM('AFEGANISTAO                                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00175',	TRIM('ALBANIA, REPUBLICA DA                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00230',	TRIM('ALEMANHA                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00310',	TRIM('BURKINA FASO                                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00370',	TRIM('ANDORRA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00400',	TRIM('ANGOLA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00418',	TRIM('ANGUILLA                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00434',	TRIM('ANTIGUA E BARBUDA                                  '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00477',	TRIM('ANTILHAS HOLANDESAS                                '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00531',	TRIM('ARABIA SAUDITA                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00590',	TRIM('ARGELIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00639',	TRIM('ARGENTINA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00647',	TRIM('ARMENIA, REPUBLICA DA                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00655',	TRIM('ARUBA                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00698',	TRIM('AUSTRALIA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00728',	TRIM('AUSTRIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00736',	TRIM('AZERBAIJAO, REPUBLICA DO                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00779',	TRIM('BAHAMAS, ILHAS                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00809',	TRIM('BAHREIN, ILHAS                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00817',	TRIM('BANGLADESH                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00833',	TRIM('BARBADOS                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00850',	TRIM('BELARUS, REPUBLICA DA                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00876',	TRIM('BELGICA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00884',	TRIM('BELIZE                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00906',	TRIM('BERMUDAS                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00930',	TRIM('MIANMAR (BIRMANIA)                                 '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00973',	TRIM('BOLIVIA, ESTADO PLURINACIONAL DA                   '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('00981',	TRIM('BOSNIA-HERZEGOVINA (REPUBLICA DA)                  '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01015',	TRIM('BOTSUANA                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01058',	TRIM('BRASIL                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01082',	TRIM('BRUNEI                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01112',	TRIM('BULGARIA, REPUBLICA DA                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01155',	TRIM('BURUNDI                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01198',	TRIM('BUTAO                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01279',	TRIM('CABO VERDE, REPUBLICA DE                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01376',	TRIM('CAYMAN, ILHAS                                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01414',	TRIM('CAMBOJA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01457',	TRIM('CAMAROES                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01490',	TRIM('CANADA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01504',	TRIM('GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)   '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01508',	TRIM('JERSEY, ILHA DO CANAL                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01511',	TRIM('CANARIAS, ILHAS                                    '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01538',	TRIM('CAZAQUISTAO, REPUBLICA DO                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01546',	TRIM('CATAR                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01589',	TRIM('CHILE                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01600',	TRIM('CHINA, REPUBLICA POPULAR                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01619',	TRIM('FORMOSA (TAIWAN)                                   '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01635',	TRIM('CHIPRE                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01651',	TRIM('COCOS(KEELING),ILHAS                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01694',	TRIM('COLOMBIA                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01732',	TRIM('COMORES, ILHAS                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01775',	TRIM('CONGO                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01830',	TRIM('COOK, ILHAS                                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01872',	TRIM('COREIA (DO NORTE), REP.POP.DEMOCRATICA             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01902',	TRIM('COREIA (DO SUL), REPUBLICA DA                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01937',	TRIM('COSTA DO MARFIM                                    '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01953',	TRIM('CROACIA (REPUBLICA DA)                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01961',	TRIM('COSTA RICA                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01988',	TRIM('COVEITE                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('01996',	TRIM('CUBA                                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02291',	TRIM('BENIN                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02321',	TRIM('DINAMARCA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02356',	TRIM('DOMINICA,ILHA                                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02399',	TRIM('EQUADOR                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02402',	TRIM('EGITO                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02437',	TRIM('ERITREIA                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02445',	TRIM('EMIRADOS ARABES UNIDOS                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02453',	TRIM('ESPANHA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02461',	TRIM('ESLOVENIA, REPUBLICA DA                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02470',	TRIM('ESLOVACA, REPUBLICA                                '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02496',	TRIM('ESTADOS UNIDOS                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02518',	TRIM('ESTONIA, REPUBLICA DA                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02534',	TRIM('ETIOPIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02550',	TRIM('FALKLAND (ILHAS MALVINAS)                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02593',	TRIM('FEROE, ILHAS                                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02674',	TRIM('FILIPINAS                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02712',	TRIM('FINLANDIA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02755',	TRIM('FRANCA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02810',	TRIM('GABAO                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02852',	TRIM('GAMBIA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02895',	TRIM('GANA                                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02917',	TRIM('GEORGIA, REPUBLICA DA                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02933',	TRIM('GIBRALTAR                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('02976',	TRIM('GRANADA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03018',	TRIM('GRECIA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03050',	TRIM('GROENLANDIA                                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03093',	TRIM('GUADALUPE                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03131',	TRIM('GUAM                                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03174',	TRIM('GUATEMALA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03255',	TRIM('GUIANA FRANCESA                                    '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03298',	TRIM('GUINE                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03310',	TRIM('GUINE-EQUATORIAL                                   '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03344',	TRIM('GUINE-BISSAU                                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03379',	TRIM('GUIANA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03417',	TRIM('HAITI                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03450',	TRIM('HONDURAS                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03514',	TRIM('HONG KONG                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03557',	TRIM('HUNGRIA, REPUBLICA DA                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03573',	TRIM('IEMEN                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03595',	TRIM('MAN, ILHA DE                                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03611',	TRIM('INDIA                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03654',	TRIM('INDONESIA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03697',	TRIM('IRAQUE                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03727',	TRIM('IRA, REPUBLICA ISLAMICA DO                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03751',	TRIM('IRLANDA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03794',	TRIM('ISLANDIA                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03832',	TRIM('ISRAEL                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03867',	TRIM('ITALIA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03913',	TRIM('JAMAICA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03964',	TRIM('JOHNSTON, ILHAS                                    '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('03999',	TRIM('JAPAO                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04030',	TRIM('JORDANIA                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04111',	TRIM('KIRIBATI                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04200',	TRIM('LAOS, REP.POP.DEMOCR.DO                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04235',	TRIM('LEBUAN,ILHAS                                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04260',	TRIM('LESOTO                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04278',	TRIM('LETONIA, REPUBLICA DA                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04316',	TRIM('LIBANO                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04340',	TRIM('LIBERIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04383',	TRIM('LIBIA                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04405',	TRIM('LIECHTENSTEIN                                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04421',	TRIM('LITUANIA, REPUBLICA DA                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04456',	TRIM('LUXEMBURGO                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04472',	TRIM('MACAU                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04499',	TRIM('MACEDONIA, ANT.REP.IUGOSLAVA                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04502',	TRIM('MADAGASCAR                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04525',	TRIM('MADEIRA, ILHA DA                                   '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04553',	TRIM('MALASIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04588',	TRIM('MALAVI                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04618',	TRIM('MALDIVAS                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04642',	TRIM('MALI                                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04677',	TRIM('MALTA                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04723',	TRIM('MARIANAS DO NORTE                                  '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04740',	TRIM('MARROCOS                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04766',	TRIM('MARSHALL,ILHAS                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04774',	TRIM('MARTINICA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04855',	TRIM('MAURICIO                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04880',	TRIM('MAURITANIA                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04885',	TRIM('MAYOTTE (ILHAS FRANCESAS)                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04901',	TRIM('MIDWAY, ILHAS                                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04936',	TRIM('MEXICO                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04944',	TRIM('MOLDAVIA, REPUBLICA DA                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04952',	TRIM('MONACO                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04979',	TRIM('MONGOLIA                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04985',	TRIM('MONTENEGRO                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('04995',	TRIM('MICRONESIA                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05010',	TRIM('MONTSERRAT,ILHAS                                   '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05053',	TRIM('MOCAMBIQUE                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05070',	TRIM('NAMIBIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05088',	TRIM('NAURU                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05118',	TRIM('CHRISTMAS,ILHA (NAVIDAD)                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05177',	TRIM('NEPAL                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05215',	TRIM('NICARAGUA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05258',	TRIM('NIGER                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05282',	TRIM('NIGERIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05312',	TRIM('NIUE,ILHA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05355',	TRIM('NORFOLK,ILHA                                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05380',	TRIM('NORUEGA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05428',	TRIM('NOVA CALEDONIA                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05452',	TRIM('PAPUA NOVA GUINE                                   '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05487',	TRIM('NOVA ZELANDIA                                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05517',	TRIM('VANUATU                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05568',	TRIM('OMA                                                '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05665',	TRIM('PACIFICO,ILHAS DO (POSSESSAO DOS EUA)              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05738',	TRIM('PAISES BAIXOS (HOLANDA)                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05754',	TRIM('PALAU                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05762',	TRIM('PAQUISTAO                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05780',	TRIM('PALESTINA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05800',	TRIM('PANAMA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05860',	TRIM('PARAGUAI                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05894',	TRIM('PERU                                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05932',	TRIM('PITCAIRN,ILHA                                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('05991',	TRIM('POLINESIA FRANCESA                                 '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06033',	TRIM('POLONIA, REPUBLICA DA                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06076',	TRIM('PORTUGAL                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06114',	TRIM('PORTO RICO                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06238',	TRIM('QUENIA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06254',	TRIM('QUIRGUIZ, REPUBLICA                                '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06289',	TRIM('REINO UNIDO                                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06408',	TRIM('REPUBLICA CENTRO-AFRICANA                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06475',	TRIM('REPUBLICA DOMINICANA                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06602',	TRIM('REUNIAO, ILHA                                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06653',	TRIM('ZIMBABUE                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06700',	TRIM('ROMENIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06750',	TRIM('RUANDA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06769',	TRIM('RUSSIA, FEDERACAO DA                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06777',	TRIM('SALOMAO, ILHAS                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06858',	TRIM('SAARA OCIDENTAL                                    '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06874',	TRIM('EL SALVADOR                                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06904',	TRIM('SAMOA                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06912',	TRIM('SAMOA AMERICANA                                    '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06955',	TRIM('SAO CRISTOVAO E NEVES,ILHAS                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('06971',	TRIM('SAN MARINO                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07005',	TRIM('SAO PEDRO E MIQUELON                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07056',	TRIM('SAO VICENTE E GRANADINAS                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07102',	TRIM('SANTA HELENA                                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07153',	TRIM('SANTA LUCIA                                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07200',	TRIM('SAO TOME E PRINCIPE, ILHAS                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07285',	TRIM('SENEGAL                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07315',	TRIM('SEYCHELLES                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07358',	TRIM('SERRA LEOA                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07370',	TRIM('SERVIA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07412',	TRIM('CINGAPURA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07447',	TRIM('SIRIA, REPUBLICA ARABE DA                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07480',	TRIM('SOMALIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07501',	TRIM('SRI LANKA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07544',	TRIM('SUAZILANDIA                                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07560',	TRIM('AFRICA DO SUL                                      '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07595',	TRIM('SUDAO                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07600',	TRIM('SUDÃO DO SUL                                       '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07641',	TRIM('SUECIA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07676',	TRIM('SUICA                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07706',	TRIM('SURINAME                                           '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07722',	TRIM('TADJIQUISTAO, REPUBLICA DO                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07765',	TRIM('TAILANDIA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07803',	TRIM('TANZANIA, REP.UNIDA DA                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07820',	TRIM('TERRITORIO BRIT.OC.INDICO                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07838',	TRIM('DJIBUTI                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07889',	TRIM('CHADE                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07919',	TRIM('TCHECA, REPUBLICA                                  '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('07951',	TRIM('TIMOR LESTE                                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08001',	TRIM('TOGO                                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08052',	TRIM('TOQUELAU,ILHAS                                     '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08109',	TRIM('TONGA                                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08150',	TRIM('TRINIDAD E TOBAGO                                  '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08206',	TRIM('TUNISIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08230',	TRIM('TURCAS E CAICOS,ILHAS                              '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08249',	TRIM('TURCOMENISTAO, REPUBLICA DO                        '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08273',	TRIM('TURQUIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08281',	TRIM('TUVALU                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08311',	TRIM('UCRANIA                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08338',	TRIM('UGANDA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08451',	TRIM('URUGUAI                                            '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08478',	TRIM('UZBEQUISTAO, REPUBLICA DO                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08486',	TRIM('VATICANO, EST.DA CIDADE DO                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08508',	TRIM('VENEZUELA                                          '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08583',	TRIM('VIETNA                                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08630',	TRIM('VIRGENS,ILHAS (BRITANICAS)                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08664',	TRIM('VIRGENS,ILHAS (E.U.A.)                             '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08702',	TRIM('FIJI                                               '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08737',	TRIM('WAKE, ILHA                                         '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08885',	TRIM('CONGO, REPUBLICA DEMOCRATICA DO                    '));
INSERT INTO PAIS_PAS(PAS_CDPAIS, PAS_NMPAIS) VALUES ('08907',	TRIM('ZAMBIA                                             '));